# Site settings
name: Oraa
description: A GitHub repository for Oraa.
baseurl: /

# Build settings
theme: jekyll-theme-minimal
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
